In [8]:
import pandas as pd
import glob
import os
from pathlib import Path

In [26]:
path = 'Resources/first_round_csvs'
all_files = glob.glob(os.path.join(path + "/*.csv"))

li = []

for filename in all_files:
    df = pd.read_csv(filename,encoding_errors='ignore', index_col=None, header=0)
    li.append(df)

first_round_df = pd.concat(li, axis=0, ignore_index=True)

In [30]:
first_round_df.sort_values(by=['Year'])

,Year,Rnd,DT,OvPck,FrRnd,RdPck,Tm,Signed,Bonus,Name,...,BA,OPS,G.1,W,L,ERA,WHIP,SV,Type,Drafted Out of
249,2000,1,NaN,24,FrRnd,24,Cardinals via Rangers,Y,"$1,375,000",*Blake Williams(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4Yr,"Texas State University (San Marcos, TX)"
226,2000,1,NaN,1,FrRnd,1,Marlins,Y,"$3,000,000",Adrian Gonzalez(minors),...,0.287,0.843,NaN,NaN,NaN,NaN,NaN,NaN,HS,"Eastlake HS (Chula Vista, CA)"
250,2000,1,NaN,25,FrRnd,25,Rangers via Mets,Y,"$1,475,000",*Scott Heard(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HS,"Rancho Bernardo HS (San Diego, CA)"
251,2000,1,NaN,26,FrRnd,26,Indians,Y,"$1,375,000",Corey Smith(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HS,"Piscataway HS (Piscataway, NJ)"
252,2000,1,NaN,27,FrRnd,27,Astros,Y,"$1,250,000",Rob Stiehl(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JC,"El Camino College (Torrance, CA)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,2015,1,NaN,17,FrRnd,17,Indians,Y,"$2,513,280",Brady Aiken(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HS,"IMG Academy (Bradenton, FL)"
157,2015,1,NaN,18,FrRnd,18,Giants,Y,"$2,333,800",Phil Bickford(minors),...,0.333,0.667,85.0,4.0,3.0,3.84,1.1,1.0,JC,"College of Southern Nevada (Henderson, NV)"
158,2015,1,NaN,19,FrRnd,19,Pirates,Y,"$2,175,000",Kevin Newman(minors),...,0.257,0.655,NaN,NaN,NaN,NaN,NaN,NaN,4Yr,"University of Arizona (Tucson, AZ)"
149,2015,1,NaN,10,FrRnd,10,Phillies,Y,"$3,231,300",Cornelius Randolph(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HS,"Griffin HS (Griffin, GA)"
180,2015,1,NaN,41,FrRnd,41,Braves,Y,"$1,600,000",Austin Riley(minors),...,0.270,0.834,NaN,NaN,NaN,NaN,NaN,NaN,HS,"DeSoto Central HS (Southaven, MS)"