In [1]:
import pandas as pd
import glob
import os

In [2]:
path = 'Resources/first_round_csvs'
all_files = glob.glob(os.path.join(path + "/*.csv"))

li = []

for filename in all_files:
    df = pd.read_csv(filename,encoding_errors='ignore', index_col=None, header=0)
    li.append(df)

first_round_df = pd.concat(li, axis=0, ignore_index=True)

In [3]:
first_round_df.sort_values(by=['Year'])

,Year,Rnd,DT,OvPck,FrRnd,RdPck,Tm,Signed,Bonus,Name,...,BA,OPS,G.1,W,L,ERA,WHIP,SV,Type,Drafted Out of
1182,2000,1,NaN,6,FrRnd,6,Devil Rays,Y,"$2,250,000",Rocco Baldelli(minors),...,0.278,0.766,NaN,NaN,NaN,NaN,NaN,NaN,HS,"Bishop Hendricken HS (Warwick, RI)"
1201,2000,1,NaN,25,FrRnd,25,Rangers via Mets,Y,"$1,475,000",*Scott Heard(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HS,"Rancho Bernardo HS (San Diego, CA)"
1202,2000,1,NaN,26,FrRnd,26,Indians,Y,"$1,375,000",Corey Smith(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HS,"Piscataway HS (Piscataway, NJ)"
1203,2000,1,NaN,27,FrRnd,27,Astros,Y,"$1,250,000",Rob Stiehl(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JC,"El Camino College (Torrance, CA)"
1204,2000,1,NaN,28,FrRnd,28,Yankees,Y,"$1,425,000",Dave Parrish(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4Yr,"University of Michigan (Ann Arbor, MI)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1028,2015,1,NaN,33,FrRnd,33,Royals,Y,"$1,825,200",Nolan Watson(minors),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HS,"Lawrence North HS (Indianapolis, IN)"
1027,2015,1,NaN,32,FrRnd,32,Pirates,Y,"$1,855,000",Ke'Bryan Hayes(minors),...,0.271,0.741,NaN,NaN,NaN,NaN,NaN,NaN,HS,"Concordia Lutheran HS (Tomball, TX)"
1026,2015,1,NaN,31,FrRnd,31,Giants,Y,"$1,400,000",Chris Shaw(minors),...,0.153,0.466,NaN,NaN,NaN,NaN,NaN,NaN,4Yr,"Boston College (Chestnut Hill, MA)"
360,2015,1,NaN,1,FrRnd,1,Diamondbacks,Y,"$6,500,000",Dansby Swanson(minors),...,0.255,0.743,NaN,NaN,NaN,NaN,NaN,NaN,4Yr,"Vanderbilt University (Nashville, TN)"
1020,2015,1,NaN,25,FrRnd,25,Orioles,Y,"$2,064,500",DJ Stewart(minors),...,0.213,0.728,NaN,NaN,NaN,NaN,NaN,NaN,4Yr,"Florida State University (Tallahassee, FL)"

In [ ]:
first_round_df.to_csv('Resources/first_round_csvs/AllFirstRoundDrafts.csv', index=False)